features:
  - 'period_begin' 
  - 'period_end'
  - 'region'
  - 'state_code'
  - 'median_sale_price'
  - 'median_list_price'
  - 'median_ppsf'
  - 'homes_sold'
  - 'inventory'
  - 'new_listings'
  - 'months_of_supply'
  - 'median_dom'
  - 'pending_sales'
  - 'avg_sale_to_list'
  - 'sold_above_list'
  - 'price_drops'
  - 'off_market_in_two_weeks'
  - 'median_sale_price_mom'
  - 'median_sale_price_yoy'
  - 'months_of_supply_mom'
  - 'months_of_supply_yoy'
  - 'homes_sold_mom'
  - 'homes_sold_yoy'
  - 'inventory_mom'
  - 'inventory_yoy'
  - 'median_dom_mom'
  - 'median_dom_yoy'
  - 'price_drops_mom'
  - 'price_drops_yoy'
  - 'pending_sales_mom'
  - 'pending_sales_yoy'
  - 'new_listings_mom'
  - 'new_listings_yoy'
  - "property_type"

target:
  - median_sale_price
  - median_list_price
